// Code generated by wit-bindgen-go. DO NOT EDIT.

package env

import (
	"go.bytecodealliance.org/cm"
	"unsafe"
)

// OptionStringShape is used for storage in variant or result types.
type OptionStringShape struct {
	_     cm.HostLayout
	shape [unsafe.Sizeof(cm.Option[string]{})]byte
}
