// Code generated by wit-bindgen-go. DO NOT EDIT.

// Package env represents the imported interface "librefang:plugin/env@0.1.0".
package env

import (
	"go.bytecodealliance.org/cm"
	hosttypes "librefang.io/plugin/go-env-greet/librefang/plugin/host-types"
)

// HostError represents the type alias "librefang:plugin/env@0.1.0#host-error".
//
// See [hosttypes.HostError] for more information.
type HostError = hosttypes.HostError

// Read represents the imported function "read".
//
// Read an env var the plugin has been granted access to. Returns
// `none` if not set; returns `capability-denied` if the var is
// outside the allowlist.
//
//	read: func(name: string) -> result<option<string>, host-error>
//
//go:nosplit
func Read(name string) (result cm.Result[OptionStringShape, cm.Option[string], HostError]) {
	name0, name1 := cm.LowerString(name)
	wasmimport_Read((*uint8)(name0), (uint32)(name1), &result)
	return
}
