// Code generated by wit-bindgen-go. DO NOT EDIT.

package env

import (
	"go.bytecodealliance.org/cm"
)

// This file contains wasmimport and wasmexport declarations for "librefang:plugin@0.1.0".

//go:wasmimport librefang:plugin/env@0.1.0 read
//go:noescape
func wasmimport_Read(name0 *uint8, name1 uint32, result *cm.Result[OptionStringShape, cm.Option[string], HostError])
