worker_processes 1;
daemon off;
events { worker_connections 1024; }
error_log /home/ubuntu/.librefang/nginx_error.log warn;
pid /home/ubuntu/.librefang/nginx.pid;

http {
    access_log /home/ubuntu/.librefang/nginx_access.log;
    client_body_temp_path /home/ubuntu/.librefang/nginx_body;
    proxy_temp_path /home/ubuntu/.librefang/nginx_proxy;
    fastcgi_temp_path /home/ubuntu/.librefang/nginx_fastcgi;
    uwsgi_temp_path /home/ubuntu/.librefang/nginx_uwsgi;
    scgi_temp_path /home/ubuntu/.librefang/nginx_scgi;

    server {
        listen 4242;
        server_name _;

        location / {
            proxy_pass http://127.0.0.1:4200;
            proxy_hide_header content-security-policy;
            add_header Content-Security-Policy "default-src 'self' * data: blob: 'unsafe-inline' 'unsafe-eval'; connect-src 'self' * ws: wss:;";
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_http_version 1.1;
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection \"upgrade\";
            proxy_read_timeout 86400;
        }
    }
}
