// Code generated by wit-bindgen-go. DO NOT EDIT.

// Package kv represents the imported interface "librefang:plugin/kv@0.1.0".
package kv

import (
	"go.bytecodealliance.org/cm"
	hosttypes "librefang.io/plugin/go-env-greet/librefang/plugin/host-types"
)

// HostError represents the type alias "librefang:plugin/kv@0.1.0#host-error".
//
// See [hosttypes.HostError] for more information.
type HostError = hosttypes.HostError

// Get represents the imported function "get".
//
// Retrieve the value associated with `key`. `none` if the key is
// not present.
//
//	get: func(key: string) -> result<option<string>, host-error>
//
//go:nosplit
func Get(key string) (result cm.Result[OptionStringShape, cm.Option[string], HostError]) {
	key0, key1 := cm.LowerString(key)
	wasmimport_Get((*uint8)(key0), (uint32)(key1), &result)
	return
}

// Set represents the imported function "set".
//
// Set the value associated with `key`. Overwrites existing values.
//
//	set: func(key: string, value: string) -> result<_, host-error>
//
//go:nosplit
func Set(key string, value string) (result cm.Result[HostError, struct{}, HostError]) {
	key0, key1 := cm.LowerString(key)
	value0, value1 := cm.LowerString(value)
	wasmimport_Set((*uint8)(key0), (uint32)(key1), (*uint8)(value0), (uint32)(value1), &result)
	return
}
