// Code generated by wit-bindgen-go. DO NOT EDIT.

package kv

import (
	"go.bytecodealliance.org/cm"
)

// This file contains wasmimport and wasmexport declarations for "librefang:plugin@0.1.0".

//go:wasmimport librefang:plugin/kv@0.1.0 get
//go:noescape
func wasmimport_Get(key0 *uint8, key1 uint32, result *cm.Result[OptionStringShape, cm.Option[string], HostError])

//go:wasmimport librefang:plugin/kv@0.1.0 set
//go:noescape
func wasmimport_Set(key0 *uint8, key1 uint32, value0 *uint8, value1 uint32, result *cm.Result[HostError, struct{}, HostError])
