name = "librefang-github-stats"
main = "index.js"
compatibility_date = "2025-01-01"
account_id = "57449de851e4289a4407a73e66baaac9"

[[d1_databases]]
binding = "DB"
database_name = "librefang-marketplace"
database_id = "1bbf40ca-963b-4b94-b65d-062b9e7bbb42"

# Runs daily at UTC 00:00
[triggers]
crons = ["0 0 * * *"]
