// Generated by `wit-bindgen` 0.57.1. DO NOT EDIT!
#include "plugin.h"
#include <stdlib.h>
#include <string.h>

// Imported Functions from `librefang:plugin/fs@0.1.0`

__attribute__((__import_module__("librefang:plugin/fs@0.1.0"), __import_name__("read")))
extern void __wasm_import_librefang_plugin_fs_read(uint8_t *, size_t, uint8_t *);

__attribute__((__import_module__("librefang:plugin/fs@0.1.0"), __import_name__("write")))
extern void __wasm_import_librefang_plugin_fs_write(uint8_t *, size_t, uint8_t *, size_t, uint8_t *);

__attribute__((__import_module__("librefang:plugin/fs@0.1.0"), __import_name__("list-entries")))
extern void __wasm_import_librefang_plugin_fs_list_entries(uint8_t *, size_t, uint8_t *);

// Imported Functions from `librefang:plugin/net@0.1.0`

__attribute__((__import_module__("librefang:plugin/net@0.1.0"), __import_name__("fetch")))
extern void __wasm_import_librefang_plugin_net_fetch(uint8_t *, size_t, uint8_t *, size_t, uint8_t *, size_t, int32_t, uint8_t *, size_t, uint8_t *);

// Imported Functions from `librefang:plugin/kv@0.1.0`

__attribute__((__import_module__("librefang:plugin/kv@0.1.0"), __import_name__("get")))
extern void __wasm_import_librefang_plugin_kv_get(uint8_t *, size_t, uint8_t *);

__attribute__((__import_module__("librefang:plugin/kv@0.1.0"), __import_name__("set")))
extern void __wasm_import_librefang_plugin_kv_set(uint8_t *, size_t, uint8_t *, size_t, uint8_t *);

// Imported Functions from `librefang:plugin/agent@0.1.0`

__attribute__((__import_module__("librefang:plugin/agent@0.1.0"), __import_name__("send")))
extern void __wasm_import_librefang_plugin_agent_send(uint8_t *, size_t, uint8_t *, size_t, uint8_t *);

__attribute__((__import_module__("librefang:plugin/agent@0.1.0"), __import_name__("spawn")))
extern void __wasm_import_librefang_plugin_agent_spawn(uint8_t *, size_t, uint8_t *);

// Imported Functions from `librefang:plugin/env@0.1.0`

__attribute__((__import_module__("librefang:plugin/env@0.1.0"), __import_name__("read")))
extern void __wasm_import_librefang_plugin_env_read(uint8_t *, size_t, uint8_t *);

// Imported Functions from `librefang:plugin/time@0.1.0`

__attribute__((__import_module__("librefang:plugin/time@0.1.0"), __import_name__("now")))
extern int64_t __wasm_import_librefang_plugin_time_now(void);

// Exported Functions from `plugin`

__attribute__((__weak__, __export_name__("cabi_post_run")))
void __wasm_export_exports_plugin_run_post_return(uint8_t * arg0) {
  switch ((int32_t) (int32_t) *((uint8_t*) (arg0 + 0))) {
    case 0: {
      break;
    }
    case 1: {
      switch ((int32_t) (int32_t) *((uint8_t*) (arg0 + sizeof(void*)))) {
        case 0: {
          if ((*((size_t*) (arg0 + (3*sizeof(void*))))) > 0) {
            free(*((uint8_t **) (arg0 + (2*sizeof(void*)))));
          }
          break;
        }
        case 1: {
          if ((*((size_t*) (arg0 + (3*sizeof(void*))))) > 0) {
            free(*((uint8_t **) (arg0 + (2*sizeof(void*)))));
          }
          break;
        }
      }
      break;
    }
  }
}

// Canonical ABI intrinsics

__attribute__((__weak__, __export_name__("cabi_realloc")))
void *cabi_realloc(void *ptr, size_t old_size, size_t align, size_t new_size) {
  (void) old_size;
  if (new_size == 0) return (void*) align;
  void *ret = realloc(ptr, new_size);
  if (!ret) abort();
  return ret;
}

__attribute__((__aligned__(sizeof(void*))))
static uint8_t RET_AREA[(4*sizeof(void*))];

// Helper Functions

void librefang_plugin_host_types_host_error_free(librefang_plugin_host_types_host_error_t *ptr) {
  switch ((int32_t) ptr->tag) {
    case 0: {
      plugin_string_free(&ptr->val.capability_denied);
      break;
    }
    case 1: {
      plugin_string_free(&ptr->val.path_denied);
      break;
    }
    case 2: {
      plugin_string_free(&ptr->val.ssrf_denied);
      break;
    }
    case 3: {
      plugin_string_free(&ptr->val.io);
      break;
    }
    case 4: {
      plugin_string_free(&ptr->val.invalid_argument);
      break;
    }
    case 6: {
      plugin_string_free(&ptr->val.internal);
      break;
    }
  }
}

void librefang_plugin_fs_host_error_free(librefang_plugin_fs_host_error_t *ptr) {
  librefang_plugin_host_types_host_error_free(ptr);
}

void plugin_list_u8_free(plugin_list_u8_t *ptr) {
  size_t list_len = ptr->len;
  if (list_len > 0) {
    uint8_t *list_ptr = ptr->ptr;
    for (size_t i = 0; i < list_len; i++) {
    }
    free(list_ptr);
  }
}

void librefang_plugin_fs_result_list_u8_host_error_free(librefang_plugin_fs_result_list_u8_host_error_t *ptr) {
  if (!ptr->is_err) {
    plugin_list_u8_free(&ptr->val.ok);
  } else {
    librefang_plugin_fs_host_error_free(&ptr->val.err);
  }
}

void librefang_plugin_fs_result_void_host_error_free(librefang_plugin_fs_result_void_host_error_t *ptr) {
  if (!ptr->is_err) {
  } else {
    librefang_plugin_fs_host_error_free(&ptr->val.err);
  }
}

void plugin_list_string_free(plugin_list_string_t *ptr) {
  size_t list_len = ptr->len;
  if (list_len > 0) {
    plugin_string_t *list_ptr = ptr->ptr;
    for (size_t i = 0; i < list_len; i++) {
      plugin_string_free(&list_ptr[i]);
    }
    free(list_ptr);
  }
}

void librefang_plugin_fs_result_list_string_host_error_free(librefang_plugin_fs_result_list_string_host_error_t *ptr) {
  if (!ptr->is_err) {
    plugin_list_string_free(&ptr->val.ok);
  } else {
    librefang_plugin_fs_host_error_free(&ptr->val.err);
  }
}

void librefang_plugin_net_host_error_free(librefang_plugin_net_host_error_t *ptr) {
  librefang_plugin_host_types_host_error_free(ptr);
}

void plugin_tuple2_string_string_free(plugin_tuple2_string_string_t *ptr) {
  plugin_string_free(&ptr->f0);
  plugin_string_free(&ptr->f1);
}

void plugin_list_tuple2_string_string_free(plugin_list_tuple2_string_string_t *ptr) {
  size_t list_len = ptr->len;
  if (list_len > 0) {
    plugin_tuple2_string_string_t *list_ptr = ptr->ptr;
    for (size_t i = 0; i < list_len; i++) {
      plugin_tuple2_string_string_free(&list_ptr[i]);
    }
    free(list_ptr);
  }
}

void plugin_option_list_u8_free(plugin_option_list_u8_t *ptr) {
  if (ptr->is_some) {
    plugin_list_u8_free(&ptr->val);
  }
}

void librefang_plugin_net_http_request_free(librefang_plugin_net_http_request_t *ptr) {
  plugin_string_free(&ptr->method);
  plugin_string_free(&ptr->url);
  plugin_list_tuple2_string_string_free(&ptr->headers);
  plugin_option_list_u8_free(&ptr->body);
}

void librefang_plugin_net_http_response_free(librefang_plugin_net_http_response_t *ptr) {
  plugin_list_tuple2_string_string_free(&ptr->headers);
  plugin_list_u8_free(&ptr->body);
}

void librefang_plugin_net_result_http_response_host_error_free(librefang_plugin_net_result_http_response_host_error_t *ptr) {
  if (!ptr->is_err) {
    librefang_plugin_net_http_response_free(&ptr->val.ok);
  } else {
    librefang_plugin_net_host_error_free(&ptr->val.err);
  }
}

void librefang_plugin_kv_host_error_free(librefang_plugin_kv_host_error_t *ptr) {
  librefang_plugin_host_types_host_error_free(ptr);
}

void plugin_option_string_free(plugin_option_string_t *ptr) {
  if (ptr->is_some) {
    plugin_string_free(&ptr->val);
  }
}

void librefang_plugin_kv_result_option_string_host_error_free(librefang_plugin_kv_result_option_string_host_error_t *ptr) {
  if (!ptr->is_err) {
    plugin_option_string_free(&ptr->val.ok);
  } else {
    librefang_plugin_kv_host_error_free(&ptr->val.err);
  }
}

void librefang_plugin_kv_result_void_host_error_free(librefang_plugin_kv_result_void_host_error_t *ptr) {
  if (!ptr->is_err) {
  } else {
    librefang_plugin_kv_host_error_free(&ptr->val.err);
  }
}

void librefang_plugin_agent_host_error_free(librefang_plugin_agent_host_error_t *ptr) {
  librefang_plugin_host_types_host_error_free(ptr);
}

void librefang_plugin_agent_result_string_host_error_free(librefang_plugin_agent_result_string_host_error_t *ptr) {
  if (!ptr->is_err) {
    plugin_string_free(&ptr->val.ok);
  } else {
    librefang_plugin_agent_host_error_free(&ptr->val.err);
  }
}

void librefang_plugin_env_host_error_free(librefang_plugin_env_host_error_t *ptr) {
  librefang_plugin_host_types_host_error_free(ptr);
}

void librefang_plugin_env_result_option_string_host_error_free(librefang_plugin_env_result_option_string_host_error_t *ptr) {
  if (!ptr->is_err) {
    plugin_option_string_free(&ptr->val.ok);
  } else {
    librefang_plugin_env_host_error_free(&ptr->val.err);
  }
}

void librefang_plugin_plugin_types_plugin_error_free(librefang_plugin_plugin_types_plugin_error_t *ptr) {
  switch ((int32_t) ptr->tag) {
    case 0: {
      plugin_string_free(&ptr->val.invalid_input);
      break;
    }
    case 1: {
      plugin_string_free(&ptr->val.internal);
      break;
    }
  }
}

void plugin_plugin_error_free(plugin_plugin_error_t *ptr) {
  librefang_plugin_plugin_types_plugin_error_free(ptr);
}

void plugin_result_void_plugin_error_free(plugin_result_void_plugin_error_t *ptr) {
  if (!ptr->is_err) {
  } else {
    plugin_plugin_error_free(&ptr->val.err);
  }
}

void plugin_string_set(plugin_string_t *ret, const char*s) {
  ret->ptr = (uint8_t*) s;
  ret->len = strlen(s);
}

void plugin_string_dup(plugin_string_t *ret, const char*s) {
  ret->len = strlen(s);
  ret->ptr = (uint8_t*) cabi_realloc(NULL, 0, 1, ret->len * 1);
  memcpy(ret->ptr, s, ret->len * 1);
}

void plugin_string_dup_n(plugin_string_t *ret, const char*s, size_t len) {
  ret->len = len;
  ret->ptr = (uint8_t*) cabi_realloc(NULL, 0, 1, ret->len * 1);
  memcpy(ret->ptr, s, ret->len * 1);
}

void plugin_string_free(plugin_string_t *ret) {
  if (ret->len > 0) {
    free(ret->ptr);
  }
  ret->ptr = NULL;
  ret->len = 0;
}

// Component Adapters

bool librefang_plugin_fs_read(plugin_string_t *path, plugin_list_u8_t *ret, librefang_plugin_fs_host_error_t *err) {
  __attribute__((__aligned__(sizeof(void*))))
  uint8_t ret_area[(4*sizeof(void*))];
  uint8_t *ptr = (uint8_t *) &ret_area;
  __wasm_import_librefang_plugin_fs_read((uint8_t *) (*path).ptr, (*path).len, ptr);
  librefang_plugin_fs_result_list_u8_host_error_t result;
  switch ((int32_t) *((uint8_t*) (ptr + 0))) {
    case 0: {
      result.is_err = false;
      result.val.ok = (plugin_list_u8_t) { (uint8_t*)(*((uint8_t **) (ptr + sizeof(void*)))), (*((size_t*) (ptr + (2*sizeof(void*))))) };
      break;
    }
    case 1: {
      result.is_err = true;
      librefang_plugin_host_types_host_error_t variant;
      variant.tag = (int32_t) *((uint8_t*) (ptr + sizeof(void*)));
      switch ((int32_t) variant.tag) {
        case 0: {
          variant.val.capability_denied = (plugin_string_t) { (uint8_t*)(*((uint8_t **) (ptr + (2*sizeof(void*))))), (*((size_t*) (ptr + (3*sizeof(void*))))) };
          break;
        }
        case 1: {
          variant.val.path_denied = (plugin_string_t) { (uint8_t*)(*((uint8_t **) (ptr + (2*sizeof(void*))))), (*((size_t*) (ptr + (3*sizeof(void*))))) };
          break;
        }
        case 2: {
          variant.val.ssrf_denied = (plugin_string_t) { (uint8_t*)(*((uint8_t **) (ptr + (2*sizeof(void*))))), (*((size_t*) (ptr + (3*sizeof(void*))))) };
          break;
        }
        case 3: {
          variant.val.io = (plugin_string_t) { (uint8_t*)(*((uint8_t **) (ptr + (2*sizeof(void*))))), (*((size_t*) (ptr + (3*sizeof(void*))))) };
          break;
        }
        case 4: {
          variant.val.invalid_argument = (plugin_string_t) { (uint8_t*)(*((uint8_t **) (ptr + (2*sizeof(void*))))), (*((size_t*) (ptr + (3*sizeof(void*))))) };
          break;
        }
        case 5: {
          break;
        }
        case 6: {
          variant.val.internal = (plugin_string_t) { (uint8_t*)(*((uint8_t **) (ptr + (2*sizeof(void*))))), (*((size_t*) (ptr + (3*sizeof(void*))))) };
          break;
        }
      }

      result.val.err = variant;
      break;
    }
  }
  if (!result.is_err) {
    *ret = result.val.ok;
    return 1;
  } else {
    *err = result.val.err;
    return 0;
  }
}

bool librefang_plugin_fs_write(plugin_string_t *path, plugin_list_u8_t *body, librefang_plugin_fs_host_error_t *err) {
  __attribute__((__aligned__(sizeof(void*))))
  uint8_t ret_area[(4*sizeof(void*))];
  uint8_t *ptr = (uint8_t *) &ret_area;
  __wasm_import_librefang_plugin_fs_write((uint8_t *) (*path).ptr, (*path).len, (uint8_t *) (*body).ptr, (*body).len, ptr);
  librefang_plugin_fs_result_void_host_error_t result;
  switch ((int32_t) *((uint8_t*) (ptr + 0))) {
    case 0: {
      result.is_err = false;
      break;
    }
    case 1: {
      result.is_err = true;
      librefang_plugin_host_types_host_error_t variant;
      variant.tag = (int32_t) *((uint8_t*) (ptr + sizeof(void*)));
      switch ((int32_t) variant.tag) {
        case 0: {
          variant.val.capability_denied = (plugin_string_t) { (uint8_t*)(*((uint8_t **) (ptr + (2*sizeof(void*))))), (*((size_t*) (ptr + (3*sizeof(void*))))) };
          break;
        }
        case 1: {
          variant.val.path_denied = (plugin_string_t) { (uint8_t*)(*((uint8_t **) (ptr + (2*sizeof(void*))))), (*((size_t*) (ptr + (3*sizeof(void*))))) };
          break;
        }
        case 2: {
          variant.val.ssrf_denied = (plugin_string_t) { (uint8_t*)(*((uint8_t **) (ptr + (2*sizeof(void*))))), (*((size_t*) (ptr + (3*sizeof(void*))))) };
          break;
        }
        case 3: {
          variant.val.io = (plugin_string_t) { (uint8_t*)(*((uint8_t **) (ptr + (2*sizeof(void*))))), (*((size_t*) (ptr + (3*sizeof(void*))))) };
          break;
        }
        case 4: {
          variant.val.invalid_argument = (plugin_string_t) { (uint8_t*)(*((uint8_t **) (ptr + (2*sizeof(void*))))), (*((size_t*) (ptr + (3*sizeof(void*))))) };
          break;
        }
        case 5: {
          break;
        }
        case 6: {
          variant.val.internal = (plugin_string_t) { (uint8_t*)(*((uint8_t **) (ptr + (2*sizeof(void*))))), (*((size_t*) (ptr + (3*sizeof(void*))))) };
          break;
        }
      }

      result.val.err = variant;
      break;
    }
  }
  if (!result.is_err) {
    return 1;
  } else {
    *err = result.val.err;
    return 0;
  }
}

bool librefang_plugin_fs_list_entries(plugin_string_t *path, plugin_list_string_t *ret, librefang_plugin_fs_host_error_t *err) {
  __attribute__((__aligned__(sizeof(void*))))
  uint8_t ret_area[(4*sizeof(void*))];
  uint8_t *ptr = (uint8_t *) &ret_area;
  __wasm_import_librefang_plugin_fs_list_entries((uint8_t *) (*path).ptr, (*path).len, ptr);
  librefang_plugin_fs_result_list_string_host_error_t result;
  switch ((int32_t) *((uint8_t*) (ptr + 0))) {
    case 0: {
      result.is_err = false;
      result.val.ok = (plugin_list_string_t) { (plugin_string_t*)(*((uint8_t **) (ptr + sizeof(void*)))), (*((size_t*) (ptr + (2*sizeof(void*))))) };
      break;
    }
    case 1: {
      result.is_err = true;
      librefang_plugin_host_types_host_error_t variant;
      variant.tag = (int32_t) *((uint8_t*) (ptr + sizeof(void*)));
      switch ((int32_t) variant.tag) {
        case 0: {
          variant.val.capability_denied = (plugin_string_t) { (uint8_t*)(*((uint8_t **) (ptr + (2*sizeof(void*))))), (*((size_t*) (ptr + (3*sizeof(void*))))) };
          break;
        }
        case 1: {
          variant.val.path_denied = (plugin_string_t) { (uint8_t*)(*((uint8_t **) (ptr + (2*sizeof(void*))))), (*((size_t*) (ptr + (3*sizeof(void*))))) };
          break;
        }
        case 2: {
          variant.val.ssrf_denied = (plugin_string_t) { (uint8_t*)(*((uint8_t **) (ptr + (2*sizeof(void*))))), (*((size_t*) (ptr + (3*sizeof(void*))))) };
          break;
        }
        case 3: {
          variant.val.io = (plugin_string_t) { (uint8_t*)(*((uint8_t **) (ptr + (2*sizeof(void*))))), (*((size_t*) (ptr + (3*sizeof(void*))))) };
          break;
        }
        case 4: {
          variant.val.invalid_argument = (plugin_string_t) { (uint8_t*)(*((uint8_t **) (ptr + (2*sizeof(void*))))), (*((size_t*) (ptr + (3*sizeof(void*))))) };
          break;
        }
        case 5: {
          break;
        }
        case 6: {
          variant.val.internal = (plugin_string_t) { (uint8_t*)(*((uint8_t **) (ptr + (2*sizeof(void*))))), (*((size_t*) (ptr + (3*sizeof(void*))))) };
          break;
        }
      }

      result.val.err = variant;
      break;
    }
  }
  if (!result.is_err) {
    *ret = result.val.ok;
    return 1;
  } else {
    *err = result.val.err;
    return 0;
  }
}

bool librefang_plugin_net_fetch(librefang_plugin_net_http_request_t *req, librefang_plugin_net_http_response_t *ret, librefang_plugin_net_host_error_t *err) {
  __attribute__((__aligned__(sizeof(void*))))
  uint8_t ret_area[(6*sizeof(void*))];
  int32_t option;
  uint8_t * option1;
  size_t option2;
  if (((*req).body).is_some) {
    const plugin_list_u8_t *payload0 = &((*req).body).val;
    option = 1;
    option1 = (uint8_t *) (*payload0).ptr;
    option2 = (*payload0).len;
  } else {
    option = 0;
    option1 = 0;
    option2 = 0;
  }
  uint8_t *ptr = (uint8_t *) &ret_area;
  __wasm_import_librefang_plugin_net_fetch((uint8_t *) ((*req).method).ptr, ((*req).method).len, (uint8_t *) ((*req).url).ptr, ((*req).url).len, (uint8_t *) ((*req).headers).ptr, ((*req).headers).len, option, option1, option2, ptr);
  librefang_plugin_net_result_http_response_host_error_t result;
  switch ((int32_t) *((uint8_t*) (ptr + 0))) {
    case 0: {
      result.is_err = false;
      result.val.ok = (librefang_plugin_net_http_response_t) {
        (uint16_t) (uint16_t) ((int32_t) *((uint16_t*) (ptr + sizeof(void*)))),
        (plugin_list_tuple2_string_string_t) (plugin_list_tuple2_string_string_t) { (plugin_tuple2_string_string_t*)(*((uint8_t **) (ptr + (2*sizeof(void*))))), (*((size_t*) (ptr + (3*sizeof(void*))))) },
        (plugin_list_u8_t) (plugin_list_u8_t) { (uint8_t*)(*((uint8_t **) (ptr + (4*sizeof(void*))))), (*((size_t*) (ptr + (5*sizeof(void*))))) },
      };
      break;
    }
    case 1: {
      result.is_err = true;
      librefang_plugin_host_types_host_error_t variant;
      variant.tag = (int32_t) *((uint8_t*) (ptr + sizeof(void*)));
      switch ((int32_t) variant.tag) {
        case 0: {
          variant.val.capability_denied = (plugin_string_t) { (uint8_t*)(*((uint8_t **) (ptr + (2*sizeof(void*))))), (*((size_t*) (ptr + (3*sizeof(void*))))) };
          break;
        }
        case 1: {
          variant.val.path_denied = (plugin_string_t) { (uint8_t*)(*((uint8_t **) (ptr + (2*sizeof(void*))))), (*((size_t*) (ptr + (3*sizeof(void*))))) };
          break;
        }
        case 2: {
          variant.val.ssrf_denied = (plugin_string_t) { (uint8_t*)(*((uint8_t **) (ptr + (2*sizeof(void*))))), (*((size_t*) (ptr + (3*sizeof(void*))))) };
          break;
        }
        case 3: {
          variant.val.io = (plugin_string_t) { (uint8_t*)(*((uint8_t **) (ptr + (2*sizeof(void*))))), (*((size_t*) (ptr + (3*sizeof(void*))))) };
          break;
        }
        case 4: {
          variant.val.invalid_argument = (plugin_string_t) { (uint8_t*)(*((uint8_t **) (ptr + (2*sizeof(void*))))), (*((size_t*) (ptr + (3*sizeof(void*))))) };
          break;
        }
        case 5: {
          break;
        }
        case 6: {
          variant.val.internal = (plugin_string_t) { (uint8_t*)(*((uint8_t **) (ptr + (2*sizeof(void*))))), (*((size_t*) (ptr + (3*sizeof(void*))))) };
          break;
        }
      }

      result.val.err = variant;
      break;
    }
  }
  if (!result.is_err) {
    *ret = result.val.ok;
    return 1;
  } else {
    *err = result.val.err;
    return 0;
  }
}

bool librefang_plugin_kv_get(plugin_string_t *key, plugin_option_string_t *ret, librefang_plugin_kv_host_error_t *err) {
  __attribute__((__aligned__(sizeof(void*))))
  uint8_t ret_area[(4*sizeof(void*))];
  uint8_t *ptr = (uint8_t *) &ret_area;
  __wasm_import_librefang_plugin_kv_get((uint8_t *) (*key).ptr, (*key).len, ptr);
  librefang_plugin_kv_result_option_string_host_error_t result;
  switch ((int32_t) *((uint8_t*) (ptr + 0))) {
    case 0: {
      result.is_err = false;
      plugin_option_string_t option;
      switch ((int32_t) *((uint8_t*) (ptr + sizeof(void*)))) {
        case 0: {
          option.is_some = false;
          break;
        }
        case 1: {
          option.is_some = true;
          option.val = (plugin_string_t) { (uint8_t*)(*((uint8_t **) (ptr + (2*sizeof(void*))))), (*((size_t*) (ptr + (3*sizeof(void*))))) };
          break;
        }
      }

      result.val.ok = option;
      break;
    }
    case 1: {
      result.is_err = true;
      librefang_plugin_host_types_host_error_t variant;
      variant.tag = (int32_t) *((uint8_t*) (ptr + sizeof(void*)));
      switch ((int32_t) variant.tag) {
        case 0: {
          variant.val.capability_denied = (plugin_string_t) { (uint8_t*)(*((uint8_t **) (ptr + (2*sizeof(void*))))), (*((size_t*) (ptr + (3*sizeof(void*))))) };
          break;
        }
        case 1: {
          variant.val.path_denied = (plugin_string_t) { (uint8_t*)(*((uint8_t **) (ptr + (2*sizeof(void*))))), (*((size_t*) (ptr + (3*sizeof(void*))))) };
          break;
        }
        case 2: {
          variant.val.ssrf_denied = (plugin_string_t) { (uint8_t*)(*((uint8_t **) (ptr + (2*sizeof(void*))))), (*((size_t*) (ptr + (3*sizeof(void*))))) };
          break;
        }
        case 3: {
          variant.val.io = (plugin_string_t) { (uint8_t*)(*((uint8_t **) (ptr + (2*sizeof(void*))))), (*((size_t*) (ptr + (3*sizeof(void*))))) };
          break;
        }
        case 4: {
          variant.val.invalid_argument = (plugin_string_t) { (uint8_t*)(*((uint8_t **) (ptr + (2*sizeof(void*))))), (*((size_t*) (ptr + (3*sizeof(void*))))) };
          break;
        }
        case 5: {
          break;
        }
        case 6: {
          variant.val.internal = (plugin_string_t) { (uint8_t*)(*((uint8_t **) (ptr + (2*sizeof(void*))))), (*((size_t*) (ptr + (3*sizeof(void*))))) };
          break;
        }
      }

      result.val.err = variant;
      break;
    }
  }
  if (!result.is_err) {
    *ret = result.val.ok;
    return 1;
  } else {
    *err = result.val.err;
    return 0;
  }
}

bool librefang_plugin_kv_set(plugin_string_t *key, plugin_string_t *value, librefang_plugin_kv_host_error_t *err) {
  __attribute__((__aligned__(sizeof(void*))))
  uint8_t ret_area[(4*sizeof(void*))];
  uint8_t *ptr = (uint8_t *) &ret_area;
  __wasm_import_librefang_plugin_kv_set((uint8_t *) (*key).ptr, (*key).len, (uint8_t *) (*value).ptr, (*value).len, ptr);
  librefang_plugin_kv_result_void_host_error_t result;
  switch ((int32_t) *((uint8_t*) (ptr + 0))) {
    case 0: {
      result.is_err = false;
      break;
    }
    case 1: {
      result.is_err = true;
      librefang_plugin_host_types_host_error_t variant;
      variant.tag = (int32_t) *((uint8_t*) (ptr + sizeof(void*)));
      switch ((int32_t) variant.tag) {
        case 0: {
          variant.val.capability_denied = (plugin_string_t) { (uint8_t*)(*((uint8_t **) (ptr + (2*sizeof(void*))))), (*((size_t*) (ptr + (3*sizeof(void*))))) };
          break;
        }
        case 1: {
          variant.val.path_denied = (plugin_string_t) { (uint8_t*)(*((uint8_t **) (ptr + (2*sizeof(void*))))), (*((size_t*) (ptr + (3*sizeof(void*))))) };
          break;
        }
        case 2: {
          variant.val.ssrf_denied = (plugin_string_t) { (uint8_t*)(*((uint8_t **) (ptr + (2*sizeof(void*))))), (*((size_t*) (ptr + (3*sizeof(void*))))) };
          break;
        }
        case 3: {
          variant.val.io = (plugin_string_t) { (uint8_t*)(*((uint8_t **) (ptr + (2*sizeof(void*))))), (*((size_t*) (ptr + (3*sizeof(void*))))) };
          break;
        }
        case 4: {
          variant.val.invalid_argument = (plugin_string_t) { (uint8_t*)(*((uint8_t **) (ptr + (2*sizeof(void*))))), (*((size_t*) (ptr + (3*sizeof(void*))))) };
          break;
        }
        case 5: {
          break;
        }
        case 6: {
          variant.val.internal = (plugin_string_t) { (uint8_t*)(*((uint8_t **) (ptr + (2*sizeof(void*))))), (*((size_t*) (ptr + (3*sizeof(void*))))) };
          break;
        }
      }

      result.val.err = variant;
      break;
    }
  }
  if (!result.is_err) {
    return 1;
  } else {
    *err = result.val.err;
    return 0;
  }
}

bool librefang_plugin_agent_send(plugin_string_t *target_agent, plugin_string_t *body, plugin_string_t *ret, librefang_plugin_agent_host_error_t *err) {
  __attribute__((__aligned__(sizeof(void*))))
  uint8_t ret_area[(4*sizeof(void*))];
  uint8_t *ptr = (uint8_t *) &ret_area;
  __wasm_import_librefang_plugin_agent_send((uint8_t *) (*target_agent).ptr, (*target_agent).len, (uint8_t *) (*body).ptr, (*body).len, ptr);
  librefang_plugin_agent_result_string_host_error_t result;
  switch ((int32_t) *((uint8_t*) (ptr + 0))) {
    case 0: {
      result.is_err = false;
      result.val.ok = (plugin_string_t) { (uint8_t*)(*((uint8_t **) (ptr + sizeof(void*)))), (*((size_t*) (ptr + (2*sizeof(void*))))) };
      break;
    }
    case 1: {
      result.is_err = true;
      librefang_plugin_host_types_host_error_t variant;
      variant.tag = (int32_t) *((uint8_t*) (ptr + sizeof(void*)));
      switch ((int32_t) variant.tag) {
        case 0: {
          variant.val.capability_denied = (plugin_string_t) { (uint8_t*)(*((uint8_t **) (ptr + (2*sizeof(void*))))), (*((size_t*) (ptr + (3*sizeof(void*))))) };
          break;
        }
        case 1: {
          variant.val.path_denied = (plugin_string_t) { (uint8_t*)(*((uint8_t **) (ptr + (2*sizeof(void*))))), (*((size_t*) (ptr + (3*sizeof(void*))))) };
          break;
        }
        case 2: {
          variant.val.ssrf_denied = (plugin_string_t) { (uint8_t*)(*((uint8_t **) (ptr + (2*sizeof(void*))))), (*((size_t*) (ptr + (3*sizeof(void*))))) };
          break;
        }
        case 3: {
          variant.val.io = (plugin_string_t) { (uint8_t*)(*((uint8_t **) (ptr + (2*sizeof(void*))))), (*((size_t*) (ptr + (3*sizeof(void*))))) };
          break;
        }
        case 4: {
          variant.val.invalid_argument = (plugin_string_t) { (uint8_t*)(*((uint8_t **) (ptr + (2*sizeof(void*))))), (*((size_t*) (ptr + (3*sizeof(void*))))) };
          break;
        }
        case 5: {
          break;
        }
        case 6: {
          variant.val.internal = (plugin_string_t) { (uint8_t*)(*((uint8_t **) (ptr + (2*sizeof(void*))))), (*((size_t*) (ptr + (3*sizeof(void*))))) };
          break;
        }
      }

      result.val.err = variant;
      break;
    }
  }
  if (!result.is_err) {
    *ret = result.val.ok;
    return 1;
  } else {
    *err = result.val.err;
    return 0;
  }
}

bool librefang_plugin_agent_spawn(plugin_string_t *manifest_ref, plugin_string_t *ret, librefang_plugin_agent_host_error_t *err) {
  __attribute__((__aligned__(sizeof(void*))))
  uint8_t ret_area[(4*sizeof(void*))];
  uint8_t *ptr = (uint8_t *) &ret_area;
  __wasm_import_librefang_plugin_agent_spawn((uint8_t *) (*manifest_ref).ptr, (*manifest_ref).len, ptr);
  librefang_plugin_agent_result_string_host_error_t result;
  switch ((int32_t) *((uint8_t*) (ptr + 0))) {
    case 0: {
      result.is_err = false;
      result.val.ok = (plugin_string_t) { (uint8_t*)(*((uint8_t **) (ptr + sizeof(void*)))), (*((size_t*) (ptr + (2*sizeof(void*))))) };
      break;
    }
    case 1: {
      result.is_err = true;
      librefang_plugin_host_types_host_error_t variant;
      variant.tag = (int32_t) *((uint8_t*) (ptr + sizeof(void*)));
      switch ((int32_t) variant.tag) {
        case 0: {
          variant.val.capability_denied = (plugin_string_t) { (uint8_t*)(*((uint8_t **) (ptr + (2*sizeof(void*))))), (*((size_t*) (ptr + (3*sizeof(void*))))) };
          break;
        }
        case 1: {
          variant.val.path_denied = (plugin_string_t) { (uint8_t*)(*((uint8_t **) (ptr + (2*sizeof(void*))))), (*((size_t*) (ptr + (3*sizeof(void*))))) };
          break;
        }
        case 2: {
          variant.val.ssrf_denied = (plugin_string_t) { (uint8_t*)(*((uint8_t **) (ptr + (2*sizeof(void*))))), (*((size_t*) (ptr + (3*sizeof(void*))))) };
          break;
        }
        case 3: {
          variant.val.io = (plugin_string_t) { (uint8_t*)(*((uint8_t **) (ptr + (2*sizeof(void*))))), (*((size_t*) (ptr + (3*sizeof(void*))))) };
          break;
        }
        case 4: {
          variant.val.invalid_argument = (plugin_string_t) { (uint8_t*)(*((uint8_t **) (ptr + (2*sizeof(void*))))), (*((size_t*) (ptr + (3*sizeof(void*))))) };
          break;
        }
        case 5: {
          break;
        }
        case 6: {
          variant.val.internal = (plugin_string_t) { (uint8_t*)(*((uint8_t **) (ptr + (2*sizeof(void*))))), (*((size_t*) (ptr + (3*sizeof(void*))))) };
          break;
        }
      }

      result.val.err = variant;
      break;
    }
  }
  if (!result.is_err) {
    *ret = result.val.ok;
    return 1;
  } else {
    *err = result.val.err;
    return 0;
  }
}

bool librefang_plugin_env_read(plugin_string_t *name, plugin_option_string_t *ret, librefang_plugin_env_host_error_t *err) {
  __attribute__((__aligned__(sizeof(void*))))
  uint8_t ret_area[(4*sizeof(void*))];
  uint8_t *ptr = (uint8_t *) &ret_area;
  __wasm_import_librefang_plugin_env_read((uint8_t *) (*name).ptr, (*name).len, ptr);
  librefang_plugin_env_result_option_string_host_error_t result;
  switch ((int32_t) *((uint8_t*) (ptr + 0))) {
    case 0: {
      result.is_err = false;
      plugin_option_string_t option;
      switch ((int32_t) *((uint8_t*) (ptr + sizeof(void*)))) {
        case 0: {
          option.is_some = false;
          break;
        }
        case 1: {
          option.is_some = true;
          option.val = (plugin_string_t) { (uint8_t*)(*((uint8_t **) (ptr + (2*sizeof(void*))))), (*((size_t*) (ptr + (3*sizeof(void*))))) };
          break;
        }
      }

      result.val.ok = option;
      break;
    }
    case 1: {
      result.is_err = true;
      librefang_plugin_host_types_host_error_t variant;
      variant.tag = (int32_t) *((uint8_t*) (ptr + sizeof(void*)));
      switch ((int32_t) variant.tag) {
        case 0: {
          variant.val.capability_denied = (plugin_string_t) { (uint8_t*)(*((uint8_t **) (ptr + (2*sizeof(void*))))), (*((size_t*) (ptr + (3*sizeof(void*))))) };
          break;
        }
        case 1: {
          variant.val.path_denied = (plugin_string_t) { (uint8_t*)(*((uint8_t **) (ptr + (2*sizeof(void*))))), (*((size_t*) (ptr + (3*sizeof(void*))))) };
          break;
        }
        case 2: {
          variant.val.ssrf_denied = (plugin_string_t) { (uint8_t*)(*((uint8_t **) (ptr + (2*sizeof(void*))))), (*((size_t*) (ptr + (3*sizeof(void*))))) };
          break;
        }
        case 3: {
          variant.val.io = (plugin_string_t) { (uint8_t*)(*((uint8_t **) (ptr + (2*sizeof(void*))))), (*((size_t*) (ptr + (3*sizeof(void*))))) };
          break;
        }
        case 4: {
          variant.val.invalid_argument = (plugin_string_t) { (uint8_t*)(*((uint8_t **) (ptr + (2*sizeof(void*))))), (*((size_t*) (ptr + (3*sizeof(void*))))) };
          break;
        }
        case 5: {
          break;
        }
        case 6: {
          variant.val.internal = (plugin_string_t) { (uint8_t*)(*((uint8_t **) (ptr + (2*sizeof(void*))))), (*((size_t*) (ptr + (3*sizeof(void*))))) };
          break;
        }
      }

      result.val.err = variant;
      break;
    }
  }
  if (!result.is_err) {
    *ret = result.val.ok;
    return 1;
  } else {
    *err = result.val.err;
    return 0;
  }
}

uint64_t librefang_plugin_time_now(void) {
  int64_t ret = __wasm_import_librefang_plugin_time_now();
  return (uint64_t) (ret);
}

__attribute__((__export_name__("run")))
uint8_t * __wasm_export_exports_plugin_run(void) {
  plugin_result_void_plugin_error_t ret;
  plugin_plugin_error_t err;
  ret.is_err = !exports_plugin_run(&err);
  if (ret.is_err) {
    ret.val.err = err;
  }
  uint8_t *ptr = (uint8_t *) &RET_AREA;
  if ((ret).is_err) {
    const plugin_plugin_error_t *payload0 = &(ret).val.err;*((int8_t*)(ptr + 0)) = 1;
    switch ((int32_t) (*payload0).tag) {
      case 0: {
        const plugin_string_t *payload1 = &(*payload0).val.invalid_input;
        *((int8_t*)(ptr + sizeof(void*))) = 0;
        *((size_t*)(ptr + (3*sizeof(void*)))) = (*payload1).len;
        *((uint8_t **)(ptr + (2*sizeof(void*)))) = (uint8_t *) (*payload1).ptr;
        break;
      }
      case 1: {
        const plugin_string_t *payload2 = &(*payload0).val.internal;
        *((int8_t*)(ptr + sizeof(void*))) = 1;
        *((size_t*)(ptr + (3*sizeof(void*)))) = (*payload2).len;
        *((uint8_t **)(ptr + (2*sizeof(void*)))) = (uint8_t *) (*payload2).ptr;
        break;
      }
    }
  } else {
    *((int8_t*)(ptr + 0)) = 0;
  }
  return ptr;
}

// Ensure that the *_component_type.o object is linked in

extern void __component_type_object_force_link_plugin(void);
__attribute__((used))
void __component_type_object_force_link_plugin_public_use_in_this_compilation_unit(void) {
  __component_type_object_force_link_plugin();
}
