// Generated by `wit-bindgen` 0.57.1. DO NOT EDIT!
#ifndef __BINDINGS_PLUGIN_H
#define __BINDINGS_PLUGIN_H
#ifdef __cplusplus
extern "C" {
#endif

#include <stdint.h>
#include <stdbool.h>
#include <stddef.h>

typedef struct plugin_string_t {
  uint8_t*ptr;
  size_t len;
} plugin_string_t;

// A failure originating from the librefang host while servicing a
// guest capability call. Variants align with `SandboxError` /
// `host_functions::dispatch` error returns in librefang-runtime.
typedef struct librefang_plugin_host_types_host_error_t {
  uint8_t tag;
  union {
    plugin_string_t     capability_denied;
    plugin_string_t     path_denied;
    plugin_string_t     ssrf_denied;
    plugin_string_t     io;
    plugin_string_t     invalid_argument;
    plugin_string_t     internal;
  } val;
} librefang_plugin_host_types_host_error_t;

// The plugin's manifest did not declare this capability.
#define LIBREFANG_PLUGIN_HOST_TYPES_HOST_ERROR_CAPABILITY_DENIED 0
// The path argument escapes the plugin's permitted sandbox root
// (path-traversal guard) or refers to a denied prefix.
#define LIBREFANG_PLUGIN_HOST_TYPES_HOST_ERROR_PATH_DENIED 1
// The URL argument resolved to a blocked SSRF target
// (loopback, link-local, RFC1918, metadata service).
#define LIBREFANG_PLUGIN_HOST_TYPES_HOST_ERROR_SSRF_DENIED 2
// Operating-system-level I/O failure.
#define LIBREFANG_PLUGIN_HOST_TYPES_HOST_ERROR_IO 3
// Argument was structurally invalid (missing field, wrong type,
// bad encoding).
#define LIBREFANG_PLUGIN_HOST_TYPES_HOST_ERROR_INVALID_ARGUMENT 4
// The operation timed out before the host could complete it.
#define LIBREFANG_PLUGIN_HOST_TYPES_HOST_ERROR_TIMEOUT 5
// Catch-all for host-internal failures the plugin should not
// try to interpret.
#define LIBREFANG_PLUGIN_HOST_TYPES_HOST_ERROR_INTERNAL 6

typedef librefang_plugin_host_types_host_error_t librefang_plugin_fs_host_error_t;

typedef struct {
  uint8_t *ptr;
  size_t len;
} plugin_list_u8_t;

typedef struct {
  bool is_err;
  union {
    plugin_list_u8_t ok;
    librefang_plugin_fs_host_error_t err;
  } val;
} librefang_plugin_fs_result_list_u8_host_error_t;

typedef struct {
  bool is_err;
  union {
    librefang_plugin_fs_host_error_t err;
  } val;
} librefang_plugin_fs_result_void_host_error_t;

typedef struct {
  plugin_string_t *ptr;
  size_t len;
} plugin_list_string_t;

typedef struct {
  bool is_err;
  union {
    plugin_list_string_t ok;
    librefang_plugin_fs_host_error_t err;
  } val;
} librefang_plugin_fs_result_list_string_host_error_t;

typedef librefang_plugin_host_types_host_error_t librefang_plugin_net_host_error_t;

typedef struct {
  plugin_string_t f0;
  plugin_string_t f1;
} plugin_tuple2_string_string_t;

typedef struct {
  plugin_tuple2_string_string_t *ptr;
  size_t len;
} plugin_list_tuple2_string_string_t;

typedef struct {
  bool is_some;
  plugin_list_u8_t val;
} plugin_option_list_u8_t;

// Plain HTTP request. Subject to SSRF guards. Bodies are bytes;
// structured types (JSON etc.) are the plugin's responsibility.
typedef struct librefang_plugin_net_http_request_t {
  plugin_string_t   method;
  plugin_string_t   url;
  plugin_list_tuple2_string_string_t   headers;
  plugin_option_list_u8_t   body;
} librefang_plugin_net_http_request_t;

typedef struct librefang_plugin_net_http_response_t {
  uint16_t   status;
  plugin_list_tuple2_string_string_t   headers;
  plugin_list_u8_t   body;
} librefang_plugin_net_http_response_t;

typedef struct {
  bool is_err;
  union {
    librefang_plugin_net_http_response_t ok;
    librefang_plugin_net_host_error_t err;
  } val;
} librefang_plugin_net_result_http_response_host_error_t;

typedef librefang_plugin_host_types_host_error_t librefang_plugin_kv_host_error_t;

typedef struct {
  bool is_some;
  plugin_string_t val;
} plugin_option_string_t;

typedef struct {
  bool is_err;
  union {
    plugin_option_string_t ok;
    librefang_plugin_kv_host_error_t err;
  } val;
} librefang_plugin_kv_result_option_string_host_error_t;

typedef struct {
  bool is_err;
  union {
    librefang_plugin_kv_host_error_t err;
  } val;
} librefang_plugin_kv_result_void_host_error_t;

typedef librefang_plugin_host_types_host_error_t librefang_plugin_agent_host_error_t;

typedef struct {
  bool is_err;
  union {
    plugin_string_t ok;
    librefang_plugin_agent_host_error_t err;
  } val;
} librefang_plugin_agent_result_string_host_error_t;

typedef librefang_plugin_host_types_host_error_t librefang_plugin_env_host_error_t;

typedef struct {
  bool is_err;
  union {
    plugin_option_string_t ok;
    librefang_plugin_env_host_error_t err;
  } val;
} librefang_plugin_env_result_option_string_host_error_t;

// A failure originating from the plugin's own `run` body.
// Distinct from `host-error` (which only the host produces).
typedef struct librefang_plugin_plugin_types_plugin_error_t {
  uint8_t tag;
  union {
    plugin_string_t     invalid_input;
    plugin_string_t     internal;
  } val;
} librefang_plugin_plugin_types_plugin_error_t;

// The plugin's input was malformed or violated invariants the
// plugin enforces.
#define LIBREFANG_PLUGIN_PLUGIN_TYPES_PLUGIN_ERROR_INVALID_INPUT 0
// The plugin encountered an unrecoverable internal condition.
// Should not normally bubble — prefer explicit variants.
#define LIBREFANG_PLUGIN_PLUGIN_TYPES_PLUGIN_ERROR_INTERNAL 1

typedef librefang_plugin_plugin_types_plugin_error_t plugin_plugin_error_t;

typedef struct {
  bool is_err;
  union {
    plugin_plugin_error_t err;
  } val;
} plugin_result_void_plugin_error_t;

// Imported Functions from `librefang:plugin/fs@0.1.0`
// Read the entire contents of `path` as bytes. Subject to
// path-traversal + capability checks.
extern bool librefang_plugin_fs_read(plugin_string_t *path, plugin_list_u8_t *ret, librefang_plugin_fs_host_error_t *err);
// Write `body` to `path`, replacing existing contents. Parent
// directories are NOT created.
extern bool librefang_plugin_fs_write(plugin_string_t *path, plugin_list_u8_t *body, librefang_plugin_fs_host_error_t *err);
// List the immediate children of `path`. Returns filenames only,
// not full paths. Named `list-entries` rather than `list`
// because `list` is a reserved keyword in WIT — collides with
// the built-in list type constructor (`list<u8>` etc.) at parse
// time.
extern bool librefang_plugin_fs_list_entries(plugin_string_t *path, plugin_list_string_t *ret, librefang_plugin_fs_host_error_t *err);

// Imported Functions from `librefang:plugin/net@0.1.0`
extern bool librefang_plugin_net_fetch(librefang_plugin_net_http_request_t *req, librefang_plugin_net_http_response_t *ret, librefang_plugin_net_host_error_t *err);

// Imported Functions from `librefang:plugin/kv@0.1.0`
// Retrieve the value associated with `key`. `none` if the key is
// not present.
extern bool librefang_plugin_kv_get(plugin_string_t *key, plugin_option_string_t *ret, librefang_plugin_kv_host_error_t *err);
// Set the value associated with `key`. Overwrites existing values.
extern bool librefang_plugin_kv_set(plugin_string_t *key, plugin_string_t *value, librefang_plugin_kv_host_error_t *err);

// Imported Functions from `librefang:plugin/agent@0.1.0`
// Send a message to another agent by id. Returns the host-issued
// message id (opaque string).
extern bool librefang_plugin_agent_send(plugin_string_t *target_agent, plugin_string_t *body, plugin_string_t *ret, librefang_plugin_agent_host_error_t *err);
// Spawn a child agent from a manifest reference. Returns the new
// agent's id.
extern bool librefang_plugin_agent_spawn(plugin_string_t *manifest_ref, plugin_string_t *ret, librefang_plugin_agent_host_error_t *err);

// Imported Functions from `librefang:plugin/env@0.1.0`
// Read an env var the plugin has been granted access to. Returns
// `none` if not set; returns `capability-denied` if the var is
// outside the allowlist.
extern bool librefang_plugin_env_read(plugin_string_t *name, plugin_option_string_t *ret, librefang_plugin_env_host_error_t *err);

// Imported Functions from `librefang:plugin/time@0.1.0`
// Wall-clock now in SECONDS since the Unix epoch. Subject to
// no capability gating — every plugin can read the clock.
// (Matches the resolution of the underlying
// `host_functions::time_now` dispatch — multiply by 1000 in the
// plugin if you need millis.)
extern uint64_t librefang_plugin_time_now(void);

// Exported Functions from `plugin`
bool exports_plugin_run(plugin_plugin_error_t *err);

// Helper Functions

void librefang_plugin_host_types_host_error_free(librefang_plugin_host_types_host_error_t *ptr);

void librefang_plugin_fs_host_error_free(librefang_plugin_fs_host_error_t *ptr);

void plugin_list_u8_free(plugin_list_u8_t *ptr);

void librefang_plugin_fs_result_list_u8_host_error_free(librefang_plugin_fs_result_list_u8_host_error_t *ptr);

void librefang_plugin_fs_result_void_host_error_free(librefang_plugin_fs_result_void_host_error_t *ptr);

void plugin_list_string_free(plugin_list_string_t *ptr);

void librefang_plugin_fs_result_list_string_host_error_free(librefang_plugin_fs_result_list_string_host_error_t *ptr);

void librefang_plugin_net_host_error_free(librefang_plugin_net_host_error_t *ptr);

void plugin_tuple2_string_string_free(plugin_tuple2_string_string_t *ptr);

void plugin_list_tuple2_string_string_free(plugin_list_tuple2_string_string_t *ptr);

void plugin_option_list_u8_free(plugin_option_list_u8_t *ptr);

void librefang_plugin_net_http_request_free(librefang_plugin_net_http_request_t *ptr);

void librefang_plugin_net_http_response_free(librefang_plugin_net_http_response_t *ptr);

void librefang_plugin_net_result_http_response_host_error_free(librefang_plugin_net_result_http_response_host_error_t *ptr);

void librefang_plugin_kv_host_error_free(librefang_plugin_kv_host_error_t *ptr);

void plugin_option_string_free(plugin_option_string_t *ptr);

void librefang_plugin_kv_result_option_string_host_error_free(librefang_plugin_kv_result_option_string_host_error_t *ptr);

void librefang_plugin_kv_result_void_host_error_free(librefang_plugin_kv_result_void_host_error_t *ptr);

void librefang_plugin_agent_host_error_free(librefang_plugin_agent_host_error_t *ptr);

void librefang_plugin_agent_result_string_host_error_free(librefang_plugin_agent_result_string_host_error_t *ptr);

void librefang_plugin_env_host_error_free(librefang_plugin_env_host_error_t *ptr);

void librefang_plugin_env_result_option_string_host_error_free(librefang_plugin_env_result_option_string_host_error_t *ptr);

void librefang_plugin_plugin_types_plugin_error_free(librefang_plugin_plugin_types_plugin_error_t *ptr);

void plugin_plugin_error_free(plugin_plugin_error_t *ptr);

void plugin_result_void_plugin_error_free(plugin_result_void_plugin_error_t *ptr);

// Sets the string `ret` to reference the input string `s` without copying it
void plugin_string_set(plugin_string_t *ret, const char*s);

// Creates a copy of the input nul-terminated string `s` and
// stores it into the component model string `ret`.
void plugin_string_dup(plugin_string_t *ret, const char*s);

// Creates a copy of the input string `s` with length `len` and
// stores it into the component model string `ret`.
// The length is specified in code units (bytes for UTF-8, 16-bit values for UTF-16).
void plugin_string_dup_n(plugin_string_t *ret, const char*s, size_t len);

// Deallocates the string pointed to by `ret`, deallocating
// the memory behind the string.
void plugin_string_free(plugin_string_t *ret);

#ifdef __cplusplus
}
#endif
#endif
