// Code generated by wit-bindgen-go. DO NOT EDIT.

package fs

import (
	"go.bytecodealliance.org/cm"
	"unsafe"
)

// HostErrorShape is used for storage in variant or result types.
type HostErrorShape struct {
	_     cm.HostLayout
	shape [unsafe.Sizeof(HostError{})]byte
}
