// Code generated by wit-bindgen-go. DO NOT EDIT.

package fs

import (
	"go.bytecodealliance.org/cm"
)

// This file contains wasmimport and wasmexport declarations for "librefang:plugin@0.1.0".

//go:wasmimport librefang:plugin/fs@0.1.0 read
//go:noescape
func wasmimport_Read(path0 *uint8, path1 uint32, result *cm.Result[HostErrorShape, cm.List[uint8], HostError])

//go:wasmimport librefang:plugin/fs@0.1.0 write
//go:noescape
func wasmimport_Write(path0 *uint8, path1 uint32, body0 *uint8, body1 uint32, result *cm.Result[HostError, struct{}, HostError])

//go:wasmimport librefang:plugin/fs@0.1.0 list-entries
//go:noescape
func wasmimport_ListEntries(path0 *uint8, path1 uint32, result *cm.Result[HostErrorShape, cm.List[string], HostError])
