// Code generated by wit-bindgen-go. DO NOT EDIT.

// Package fs represents the imported interface "librefang:plugin/fs@0.1.0".
package fs

import (
	"go.bytecodealliance.org/cm"
	hosttypes "librefang.io/plugin/go-env-greet/librefang/plugin/host-types"
)

// HostError represents the type alias "librefang:plugin/fs@0.1.0#host-error".
//
// See [hosttypes.HostError] for more information.
type HostError = hosttypes.HostError

// Read represents the imported function "read".
//
// Read the entire contents of `path` as bytes. Subject to
// path-traversal + capability checks.
//
//	read: func(path: string) -> result<list<u8>, host-error>
//
//go:nosplit
func Read(path string) (result cm.Result[HostErrorShape, cm.List[uint8], HostError]) {
	path0, path1 := cm.LowerString(path)
	wasmimport_Read((*uint8)(path0), (uint32)(path1), &result)
	return
}

// Write represents the imported function "write".
//
// Write `body` to `path`, replacing existing contents. Parent
// directories are NOT created.
//
//	write: func(path: string, body: list<u8>) -> result<_, host-error>
//
//go:nosplit
func Write(path string, body cm.List[uint8]) (result cm.Result[HostError, struct{}, HostError]) {
	path0, path1 := cm.LowerString(path)
	body0, body1 := cm.LowerList(body)
	wasmimport_Write((*uint8)(path0), (uint32)(path1), (*uint8)(body0), (uint32)(body1), &result)
	return
}

// ListEntries represents the imported function "list-entries".
//
// List the immediate children of `path`. Returns filenames only,
// not full paths. Named `list-entries` rather than `list`
// because `list` is a reserved keyword in WIT — collides with
// the built-in list type constructor (`list<u8>` etc.) at parse
// time.
//
//	list-entries: func(path: string) -> result<list<string>, host-error>
//
//go:nosplit
func ListEntries(path string) (result cm.Result[HostErrorShape, cm.List[string], HostError]) {
	path0, path1 := cm.LowerString(path)
	wasmimport_ListEntries((*uint8)(path0), (uint32)(path1), &result)
	return
}
