// Code generated by wit-bindgen-go. DO NOT EDIT.

package plugin

import (
	"go.bytecodealliance.org/cm"
)

// This file contains wasmimport and wasmexport declarations for "librefang:plugin@0.1.0".

//go:wasmexport run
//export run
func wasmexport_Run() (result *cm.Result[PluginError, struct{}, PluginError]) {
	result_ := Exports.Run()
	result = &result_
	return
}
