// Code generated by wit-bindgen-go. DO NOT EDIT.

package plugin

import (
	"go.bytecodealliance.org/cm"
)

// Exports represents the caller-defined exports from "librefang:plugin/plugin@0.1.0".
var Exports struct {
	// Run represents the caller-defined, exported function "run".
	//
	// The single entry point. The host invokes this after binding
	// the imports the manifest declared. Returning an error surfaces
	// to the host as `ExecutionResult::Err(plugin-error)`.
	//
	//	run: func() -> result<_, plugin-error>
	Run func() (result cm.Result[PluginError, struct{}, PluginError])
}
