// Code generated by wit-bindgen-go. DO NOT EDIT.

// Package plugin represents the world "librefang:plugin/plugin@0.1.0".
package plugin

import (
	plugintypes "librefang.io/plugin/go-env-greet/librefang/plugin/plugin-types"
)

// PluginError represents the type alias "librefang:plugin/plugin@0.1.0#plugin-error".
//
// See [plugintypes.PluginError] for more information.
type PluginError = plugintypes.PluginError
