#!/bin/sh
set -e

CONFIG="${LIBREFANG_HOME:-/data}/config.toml"

# Auto-generate config.toml on first boot if missing
if [ ! -f "$CONFIG" ]; then
  mkdir -p "$(dirname "$CONFIG")"

  # Detect best available provider from env vars
  if [ -n "$OPENROUTER_API_KEY" ]; then
    PROVIDER="openrouter"
    MODEL="${LIBREFANG_MODEL:-openrouter/stepfun/step-3.5-flash:free}"
    KEY_ENV="OPENROUTER_API_KEY"
  elif [ -n "$GROQ_API_KEY" ]; then
    PROVIDER="groq"
    MODEL="${LIBREFANG_MODEL:-llama-3.3-70b-versatile}"
    KEY_ENV="GROQ_API_KEY"
  elif [ -n "$ANTHROPIC_API_KEY" ]; then
    PROVIDER="anthropic"
    MODEL="${LIBREFANG_MODEL:-claude-sonnet-4-20250514}"
    KEY_ENV="ANTHROPIC_API_KEY"
  elif [ -n "$OPENAI_API_KEY" ]; then
    PROVIDER="openai"
    MODEL="${LIBREFANG_MODEL:-gpt-4o}"
    KEY_ENV="OPENAI_API_KEY"
  elif [ -n "$DEEPSEEK_API_KEY" ]; then
    PROVIDER="deepseek"
    MODEL="${LIBREFANG_MODEL:-deepseek-chat}"
    KEY_ENV="DEEPSEEK_API_KEY"
  elif [ -n "$GEMINI_API_KEY" ]; then
    PROVIDER="gemini"
    MODEL="${LIBREFANG_MODEL:-gemini-2.5-flash}"
    KEY_ENV="GEMINI_API_KEY"
  else
    PROVIDER="openrouter"
    MODEL="openrouter/stepfun/step-3.5-flash:free"
    KEY_ENV="OPENROUTER_API_KEY"
  fi

  cat > "$CONFIG" <<EOF
# Auto-generated by LibreFang Docker entrypoint
api_listen = "0.0.0.0:4545"
log_level = "info"

[default_model]
provider = "$PROVIDER"
model = "$MODEL"
api_key_env = "$KEY_ENV"

[memory]
decay_rate = 0.05
EOF

  echo "Generated $CONFIG (provider=$PROVIDER, model=$MODEL)"
fi

exec "$@"
