// Code generated by wit-bindgen-go. DO NOT EDIT.

// Package hosttypes represents the imported interface "librefang:plugin/host-types@0.1.0".
//
// File: host.wit
// Typed Component Model interfaces exposing the librefang host's
// capability-checked API surface to WASM plugins.
//
// Semver discipline (see wit/README.md for the full policy):
// - 0.1.x is additive-only — new functions / new variants on
// `host-error` and `plugin-error` are OK; renaming or removing
// anything requires a 0.2.0 bump and a deprecation window.
//
// Parameter shapes mirror the existing `host_functions::dispatch` JSON-RPC
// surface in librefang-runtime exactly. Phase 5 deliberately does NOT
// redesign the surface; the WIT layer is a typed shim over the existing
// dispatch.
//
// Single-package layout: WIT requires every .wit file in a flat
// directory to share one package identifier. The host interfaces and
// the plugin world live under `librefang:plugin@0.1.0` together. A
// future split into separate packages would require adopting the
// `wit/deps/<owner>/<pkg>/...` layout.
package hosttypes

import (
	"go.bytecodealliance.org/cm"
)

// HostError represents the variant "librefang:plugin/host-types@0.1.0#host-error".
//
// A failure originating from the librefang host while servicing a
// guest capability call. Variants align with `SandboxError` /
// `host_functions::dispatch` error returns in librefang-runtime.
//
//	variant host-error {
//		capability-denied(string),
//		path-denied(string),
//		ssrf-denied(string),
//		io(string),
//		invalid-argument(string),
//		timeout,
//		internal(string),
//	}
type HostError cm.Variant[uint8, string, string]

// HostErrorCapabilityDenied returns a [HostError] of case "capability-denied".
//
// The plugin's manifest did not declare this capability.
func HostErrorCapabilityDenied(data string) HostError {
	return cm.New[HostError](0, data)
}

// CapabilityDenied returns a non-nil *[string] if [HostError] represents the variant case "capability-denied".
func (self *HostError) CapabilityDenied() *string {
	return cm.Case[string](self, 0)
}

// HostErrorPathDenied returns a [HostError] of case "path-denied".
//
// The path argument escapes the plugin's permitted sandbox root
// (path-traversal guard) or refers to a denied prefix.
func HostErrorPathDenied(data string) HostError {
	return cm.New[HostError](1, data)
}

// PathDenied returns a non-nil *[string] if [HostError] represents the variant case "path-denied".
func (self *HostError) PathDenied() *string {
	return cm.Case[string](self, 1)
}

// HostErrorSsrfDenied returns a [HostError] of case "ssrf-denied".
//
// The URL argument resolved to a blocked SSRF target
// (loopback, link-local, RFC1918, metadata service).
func HostErrorSsrfDenied(data string) HostError {
	return cm.New[HostError](2, data)
}

// SsrfDenied returns a non-nil *[string] if [HostError] represents the variant case "ssrf-denied".
func (self *HostError) SsrfDenied() *string {
	return cm.Case[string](self, 2)
}

// HostErrorIO returns a [HostError] of case "io".
//
// Operating-system-level I/O failure.
func HostErrorIO(data string) HostError {
	return cm.New[HostError](3, data)
}

// IO returns a non-nil *[string] if [HostError] represents the variant case "io".
func (self *HostError) IO() *string {
	return cm.Case[string](self, 3)
}

// HostErrorInvalidArgument returns a [HostError] of case "invalid-argument".
//
// Argument was structurally invalid (missing field, wrong type,
// bad encoding).
func HostErrorInvalidArgument(data string) HostError {
	return cm.New[HostError](4, data)
}

// InvalidArgument returns a non-nil *[string] if [HostError] represents the variant case "invalid-argument".
func (self *HostError) InvalidArgument() *string {
	return cm.Case[string](self, 4)
}

// HostErrorTimeout returns a [HostError] of case "timeout".
//
// The operation timed out before the host could complete it.
func HostErrorTimeout() HostError {
	var data struct{}
	return cm.New[HostError](5, data)
}

// Timeout returns true if [HostError] represents the variant case "timeout".
func (self *HostError) Timeout() bool {
	return self.Tag() == 5
}

// HostErrorInternal returns a [HostError] of case "internal".
//
// Catch-all for host-internal failures the plugin should not
// try to interpret.
func HostErrorInternal(data string) HostError {
	return cm.New[HostError](6, data)
}

// Internal returns a non-nil *[string] if [HostError] represents the variant case "internal".
func (self *HostError) Internal() *string {
	return cm.Case[string](self, 6)
}

var _HostErrorStrings = [7]string{
	"capability-denied",
	"path-denied",
	"ssrf-denied",
	"io",
	"invalid-argument",
	"timeout",
	"internal",
}

// String implements [fmt.Stringer], returning the variant case name of v.
func (v HostError) String() string {
	return _HostErrorStrings[v.Tag()]
}
