#!/usr/bin/env bash
# Corpus test for scripts/hooks/commit-msg.
#
# Refs docs/issues/commit-msg-attribution-regex.md sub-finding "this":
# the original regex used `Claude[[:space:]]+Code` which required at least
# one space, so the zero-space variant `ClaudeCode` slipped through. After
# the fix the space class is `*` (zero or more) and all spacing variants
# are blocked equally.
#
# The hook is case-insensitive (`grep -iE`), so casings vary in the corpus
# below to lock that behavior in too.
set -euo pipefail

# Resolve hook path relative to repo root so the test can be run from
# anywhere (e.g. `bash scripts/tests/commit-msg-attribution.sh` from root,
# or invoked by CI from a different cwd).
repo_root=$(cd "$(dirname "$0")/../.." && pwd)
HOOK="$repo_root/scripts/hooks/commit-msg"

if [ ! -x "$HOOK" ]; then
  echo "FAIL: hook not executable at $HOOK" >&2
  exit 1
fi

tmpdir=$(mktemp -d)
trap 'rm -rf "$tmpdir"' EXIT
hook_log="$tmpdir/hook.log"

show_hook_log() {
  if [[ -s "$hook_log" ]]; then
    echo "----- hook output -----" >&2
    cat "$hook_log" >&2
  fi
}

run() {
  local msg="$1"
  local file="$tmpdir/msg"
  printf '%s\n' "$msg" > "$file"
  # A human author identity is forced for the message corpus so those cases test the message regex alone, independent of whoever runs the script.
  set +e
  GIT_AUTHOR_NAME="Test Human" GIT_AUTHOR_EMAIL="human@example.com" \
    "$HOOK" "$file" >"$hook_log" 2>&1
  local rc=$?
  set -e
  return "$rc"
}

# Run the hook against a clean message with a given author identity, to exercise the author check rather than the message regex.
run_as() {
  local name="$1" email="$2"
  local file="$tmpdir/msg"
  printf '%s\n' "fix(api): a perfectly clean message" > "$file"
  set +e
  GIT_AUTHOR_NAME="$name" GIT_AUTHOR_EMAIL="$email" "$HOOK" "$file" \
    >"$hook_log" 2>&1
  local rc=$?
  set -e
  return "$rc"
}

# Should-reject corpus.
#
# - The 🤖 ... Code variants exercise the `[[:space:]]*` fix directly:
#   zero spaces (the bug), single space (status quo), and double space.
# - Co-Authored-By and "Generated with Claude" exercise the other two
#   alternations of the same regex.
# - Mixed case locks in the `-i` flag.
REJECT_CORPUS=(
  "🤖 ClaudeCode"
  "🤖 Claude Code"
  "🤖 Claude  Code"
  "🤖 claudecode"
  "Co-Authored-By: Claude <noreply@anthropic.com>"
  "Co-Authored-By: Someone <noreply@anthropic.com>"
  "Generated with Claude Code"
  "generated with claude"
  # The "by" variants. The regex spelled only "Generated with", and the footer
  # the harness actually emits says "Generated by", so the guard reported clean
  # while 285 PRs and issues went out carrying the watermark.
  "Generated by Claude Code"
  "generated by claude"
  "_Generated by [Claude Code](https://claude.ai/code)_"
  # Footer shape with no "Generated" lead-in at all.
  "See [Claude Code](https://claude.ai/code)"
  $'fix(api): real change\n\nSigned-off-by: Claude <noreply+automation@anthropic.com>'
  $'fix(api): real change\n\nAuthored-By: Claude Code <human@example.com>'
  $'fix(api): real change\n\nHelped-by: Anthropic <human@example.com>'
  $'fix(api): real change\n\nGenerated-by: Claude Code <human@example.com>'
  $'fix(api): real change\n\nCo-Authored-By: Build Bot <claude+automation@anthropic.com>'
  $'fix(api): real change\n\nReviewed-by: Claude Code <human@example.com>'
  $'fix(api): real change\n\nAssisted-by : Anthropic <human@example.com>'
  $'fix(api): real change\n\nAI-Generated-By: Build Bot <noreply+automation@anthropic.com>'
)

for bad in "${REJECT_CORPUS[@]}"; do
  if run "$bad"; then
    echo "FAIL: hook accepted attribution: $bad" >&2
    show_hook_log
    exit 1
  fi
done

# Should-accept corpus. Plain conventional commits and unrelated mentions
# of the word "code" must not trigger the guard.
ACCEPT_CORPUS=(
  "fix(api): something"
  "feat: add foo"
  "refactor(kernel): tidy code paths"
  "docs: mention Anthropic API as one option"
  "docs: explain Reviewed-by behavior for the Anthropic provider"
  # The footer alternative is matched by shape — link text plus host — so a real
  # link to a claude.ai artifact, which has different link text and a
  # /code/artifact/… path, must still be allowed through.
  "docs: link the writeup at https://claude.ai/code/artifact/2959f883"
  "docs: see [the verification report](https://claude.ai/code/artifact/2959f883)"
)

for ok in "${ACCEPT_CORPUS[@]}"; do
  if ! run "$ok"; then
    echo "FAIL: hook rejected legit message: $ok" >&2
    show_hook_log
    exit 1
  fi
done

# Author-identity corpus.
# The message is clean in every one of these, so a rejection can only come from the author check — which is the point: a commit authored as Claude carries no attribution string in its message and still lands "Claude <noreply@anthropic.com>" in `git log` and `git blame`.
REJECT_AUTHORS=(
  "Claude|noreply@anthropic.com"
  "Claude|someone@example.com"
  "Claude Code|dev@example.com"
  "claude code|dev@example.com"
  "ClaudeCode|dev@example.com"
  "Claude AI|dev@example.com"
  "Claude Haiku|dev@example.com"
  "Build Bot Claude Sonnet|dev@example.com"
  "Claude Opus 5|dev@example.com"
  "Anthropic|dev@example.com"
  "Evan Hu|noreply@anthropic.com"
  "Evan Hu|noreply+claude@anthropic.com"
  "Evan Hu|claude+ci@anthropic.com"
  # Version-then-family naming, which Anthropic has also shipped ("Claude 3.5 Sonnet", "Claude 3 Opus"), squashes to "claude35sonnet" / "claude3opus" — a family-word-anchored-to-end pattern is needed to catch this alongside the family-then-version form above.
  "Claude 3.5 Sonnet|dev@example.com"
  "Claude 3 Opus|dev@example.com"
  "claude-3-5-sonnet|dev@example.com"
)

for entry in "${REJECT_AUTHORS[@]}"; do
  IFS='|' read -r name email extra <<<"$entry"
  if [[ -n "${extra:-}" ]]; then
    echo "FAIL: malformed author corpus entry: $entry" >&2
    exit 1
  fi
  if run_as "$name" "$email"; then
    echo "FAIL: hook accepted AI author identity: $entry" >&2
    show_hook_log
    exit 1
  fi
done

# Names that merely start with the same letters, and humans who really do have an anthropic.com address, must still be able to commit — the check is on the whole name and on the bot mailbox, not on substrings or on the domain.
ACCEPT_AUTHORS=(
  "Evan Hu|e-hu@unext.jp"
  "Claudia Schiffer|claudia@example.com"
  "Claudio Ranieri|claudio@example.com"
  "Jane Doe|jane@anthropic.com"
  "Claude Dubois|claude.dubois@anthropic.com"
)

for entry in "${ACCEPT_AUTHORS[@]}"; do
  IFS='|' read -r name email extra <<<"$entry"
  if [[ -n "${extra:-}" ]]; then
    echo "FAIL: malformed author corpus entry: $entry" >&2
    exit 1
  fi
  if ! run_as "$name" "$email"; then
    echo "FAIL: hook rejected legit author identity: $entry" >&2
    show_hook_log
    exit 1
  fi
done

echo "OK: $(basename "$0")"
