#!/usr/bin/env python3
"""Corpus test for the attribution rules in `.claude/hooks/lib/check-bash-rules.py`.

The git-side hooks under `scripts/hooks/` have had a corpus test since #3400.
The Claude Code PreToolUse layer had none, and two defects lived in the gap:

1. `_ATTRIBUTION_RE` matched `Generated with .{0,40}Claude` while the footer
   the harness emits reads `_Generated by [Claude Code](https://claude.ai/code)_`.
   Neither the Python rule nor the shell hook spelled "by", so the guard
   reported clean and the watermark reached 285 PRs and issues.

2. `rule_claude_attribution` inspects only `-m` / `--message` on `git commit`.
   CLAUDE.md forbids attribution in PR bodies, issues and review comments too,
   and *mandates* `--body-file` for any body containing markdown — so the
   convention-following command was the one guaranteed to bypass the check.
   `rule_gh_body_attribution` closes that, reading the file the flag points at.

The Python regex had also drifted from its shell counterpart: it required
`Claude\\s+Code` where the shell hook allowed `[[:space:]]*`, so `ClaudeCode`
was blocked by `scripts/hooks/commit-msg` and waved through here. Both spell
zero-or-more now, and the corpus below pins them together.
"""

from __future__ import annotations

import os
import subprocess
import sys
import tempfile

# scripts/tests/<this file> -> repo root is three levels up.
REPO_ROOT = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
LIB = os.path.join(REPO_ROOT, ".claude", "hooks", "lib", "check-bash-rules.py")

# The rule set guard-bash-safety.sh actually passes, so this test fails if a
# rule is added to the library but never wired into the hook that runs it.
HOOK = os.path.join(REPO_ROOT, ".claude", "hooks", "guard-bash-safety.sh")

FOOTER = "_Generated by [Claude Code](https://claude.ai/code)_"

failures: list[str] = []


def rules_from_hook() -> str:
    with open(HOOK, "r", encoding="utf-8") as fh:
        for line in fh:
            if line.startswith("rules="):
                return line.split("=", 1)[1].strip().strip('"')
    raise SystemExit(f"FAIL: no rules= line found in {HOOK}")


RULES = rules_from_hook()


def verdict(cmd: str) -> bool:
    """True when the guard blocks `cmd`.

    check-bash-rules.py is contractually exit-0 and signals a hit by printing,
    so the presence of stdout is the verdict.
    """
    proc = subprocess.run(
        [sys.executable, LIB, "--rules", RULES],
        input=cmd,
        capture_output=True,
        text=True,
    )
    if proc.returncode != 0:
        failures.append(f"library exited {proc.returncode} on: {cmd}\n{proc.stderr}")
        return False
    return bool(proc.stdout.strip())


def expect(blocked: bool, cmd: str, why: str) -> None:
    got = verdict(cmd)
    if got != blocked:
        want = "BLOCK" if blocked else "pass"
        failures.append(f"expected {want} ({why}) but got {'BLOCK' if got else 'pass'}: {cmd}")


def main() -> int:
    if "gh-body-attribution" not in RULES:
        failures.append(
            "gh-body-attribution is not in guard-bash-safety.sh's rules= list, "
            "so the rule exists in the library but never runs"
        )

    with tempfile.TemporaryDirectory() as tmp:
        dirty = os.path.join(tmp, "dirty.md")
        clean = os.path.join(tmp, "clean.md")
        with open(dirty, "w", encoding="utf-8") as fh:
            fh.write(f"Real body prose.\n\n{FOOTER}\n")
        with open(clean, "w", encoding="utf-8") as fh:
            fh.write("Real body prose with no attribution at all.\n")

        # --- the footer must be caught wherever it can be published ---------
        for noun, verb in (
            ("pr", "create"),
            ("pr", "edit"),
            ("pr", "comment"),
            ("pr", "review"),
            ("issue", "create"),
            ("issue", "edit"),
            ("issue", "comment"),
            ("release", "create"),
            ("release", "edit"),
        ):
            expect(True, f"gh {noun} {verb} 1 --body-file {dirty}",
                   f"footer via --body-file on gh {noun} {verb}")
            expect(True, f"gh {noun} {verb} 1 --body-file={dirty}",
                   f"footer via --body-file= on gh {noun} {verb}")
            expect(True, f"gh {noun} {verb} 1 -F {dirty}",
                   f"footer via -F on gh {noun} {verb}")
            expect(True, f"gh {noun} {verb} 1 --body '{FOOTER}'",
                   f"footer inline on gh {noun} {verb}")
            expect(False, f"gh {noun} {verb} 1 --body-file {clean}",
                   f"clean body on gh {noun} {verb}")

        # --- the by/with blind spot, in the commit-message rule -------------
        for msg in (
            "Generated by Claude Code",
            "generated by claude",
            "Generated with Claude Code",
            FOOTER,
            "See [Claude Code](https://claude.ai/code)",
            # Drifted from the shell hook: `\s+` blocked these there, not here.
            "\N{ROBOT FACE} ClaudeCode",
            "\N{ROBOT FACE} claudecode",
            "\N{ROBOT FACE} Claude Code",
            "Co-Authored-By: Claude <noreply@anthropic.com>",
        ):
            expect(True, f"git commit -m 'fix: x\n\n{msg}'", f"commit message carrying {msg!r}")

        # --- no false positives --------------------------------------------
        expect(False, "gh pr list --state open --limit 50", "a read-only listing")
        expect(False, "gh api repos/librefang/librefang/actions/runs", "a read-only api call")
        expect(False, "gh pr merge 1 --auto --squash", "--auto merge stays allowed")
        expect(False, f"gh pr create --body-file {os.path.join(tmp, 'missing.md')}",
               "an unreadable body-file is not treated as a hit")
        expect(False, "gh pr create --body-file -", "stdin body cannot be inspected, must not block")
        # Footer matched by shape, so a genuine claude.ai artifact link, which
        # carries different link text and a /code/artifact/… path, still passes.
        expect(False,
               "gh pr comment 1 --body 'see [the report](https://claude.ai/code/artifact/2959f883)'",
               "an artifact link is not the footer")
        expect(False, "git commit -m 'refactor(kernel): tidy code paths'",
               "the word code alone is not attribution")
        expect(False, "git commit -m 'docs: mention Anthropic API as one option'",
               "naming the vendor in prose is not attribution")

        # --- pre-existing rules must still fire ----------------------------
        expect(True, "git push --force origin main", "force-push-main regression check")
        expect(True, "git commit --no-verify -m x", "no-verify regression check")
        expect(True, "git add -A", "broad-git-add regression check")
        expect(True, "rm -rf target", "rm-rf-dangerous regression check")

    if failures:
        for f in failures:
            print(f"FAIL: {f}", file=sys.stderr)
        print(f"\n{len(failures)} failure(s)", file=sys.stderr)
        return 1
    print(f"OK: {os.path.basename(__file__)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
