// Code generated by wit-bindgen-go. DO NOT EDIT.

// Package plugintypes represents the imported interface "librefang:plugin/plugin-types@0.1.0".
//
// File: world.wit
// Canonical Component Model world a librefang plugin targets.
// A plugin imports any subset of the librefang:plugin interfaces it
// needs (declared in its skill.toml `capabilities` field — Phase-5
// C-005) and exports a single `run` entry point.
// See host.wit for the interface definitions.
package plugintypes

import (
	"go.bytecodealliance.org/cm"
)

// PluginError represents the variant "librefang:plugin/plugin-types@0.1.0#plugin-error".
//
// A failure originating from the plugin's own `run` body.
// Distinct from `host-error` (which only the host produces).
//
//	variant plugin-error {
//		invalid-input(string),
//		internal(string),
//	}
type PluginError cm.Variant[uint8, string, string]

// PluginErrorInvalidInput returns a [PluginError] of case "invalid-input".
//
// The plugin's input was malformed or violated invariants the
// plugin enforces.
func PluginErrorInvalidInput(data string) PluginError {
	return cm.New[PluginError](0, data)
}

// InvalidInput returns a non-nil *[string] if [PluginError] represents the variant case "invalid-input".
func (self *PluginError) InvalidInput() *string {
	return cm.Case[string](self, 0)
}

// PluginErrorInternal returns a [PluginError] of case "internal".
//
// The plugin encountered an unrecoverable internal condition.
// Should not normally bubble — prefer explicit variants.
func PluginErrorInternal(data string) PluginError {
	return cm.New[PluginError](1, data)
}

// Internal returns a non-nil *[string] if [PluginError] represents the variant case "internal".
func (self *PluginError) Internal() *string {
	return cm.Case[string](self, 1)
}

var _PluginErrorStrings = [2]string{
	"invalid-input",
	"internal",
}

// String implements [fmt.Stringer], returning the variant case name of v.
func (v PluginError) String() string {
	return _PluginErrorStrings[v.Tag()]
}
