name = "librefang-marketplace"
main = "index.js"
compatibility_date = "2025-01-01"
account_id = "3ee9bb524a4fb2a9d685ce1f82b52581"

[[d1_databases]]
binding = "DB"
database_name = "librefang-marketplace"
database_id = "91df0bc6-e658-4463-9eba-22d5476d420a"

[vars]
GITHUB_CLIENT_ID = "Iv1.3683b4ad4a41e982"

# Weekly stats aggregation
[triggers]
crons = ["0 1 * * SUN"]
