use std::path::Path;

async fn remove_if_present(path: &Path) {
    if let Err(error) = tokio::fs::remove_file(path).await {
        if error.kind() != std::io::ErrorKind::NotFound {
            tracing::warn!(%error, path = %path.display(), "failed to clean up upload staging file");
        }
    }
}

/// Persist daemon-generated bytes and their explicit shared-access metadata.
pub(crate) async fn save_shared_upload(
    upload_dir: &Path,
    bytes: &[u8],
    content_type: &str,
    filename: &str,
) -> Result<String, String> {
    tokio::fs::create_dir_all(upload_dir)
        .await
        .map_err(|error| format!("Failed to create upload directory: {error}"))?;

    let file_id = uuid::Uuid::new_v4().to_string();
    let data_path = upload_dir.join(librefang_types::media::on_disk_name(
        &file_id,
        content_type,
        filename,
    ));
    if let Err(error) = tokio::fs::write(&data_path, bytes).await {
        remove_if_present(&data_path).await;
        return Err(format!("Failed to write upload file: {error}"));
    }

    let metadata = librefang_types::media::UploadMetadata {
        filename: filename.to_string(),
        content_type: content_type.to_string(),
        uploaded_by: None,
    };
    let metadata_bytes = match serde_json::to_vec(&metadata) {
        Ok(bytes) => bytes,
        Err(error) => {
            remove_if_present(&data_path).await;
            return Err(format!("Failed to serialize upload metadata: {error}"));
        }
    };
    let metadata_path = librefang_types::media::upload_metadata_path(upload_dir, &file_id);
    let metadata_temp = upload_dir.join(format!(".{file_id}.meta.{}.tmp", uuid::Uuid::new_v4()));
    if let Err(error) = tokio::fs::write(&metadata_temp, metadata_bytes).await {
        remove_if_present(&metadata_temp).await;
        remove_if_present(&data_path).await;
        return Err(format!("Failed to write upload metadata: {error}"));
    }
    if let Err(error) = tokio::fs::rename(&metadata_temp, &metadata_path).await {
        remove_if_present(&metadata_temp).await;
        remove_if_present(&data_path).await;
        return Err(format!("Failed to publish upload metadata: {error}"));
    }

    Ok(format!("/api/uploads/{file_id}"))
}

#[cfg(test)]
mod tests {
    use super::*;

    #[tokio::test]
    async fn shared_upload_persists_bytes_and_explicit_shared_metadata() {
        let dir = tempfile::tempdir().unwrap();
        let url = save_shared_upload(dir.path(), b"png bytes", "image/png", "generated.png")
            .await
            .unwrap();
        let file_id = url.strip_prefix("/api/uploads/").unwrap();
        assert!(uuid::Uuid::parse_str(file_id).is_ok());
        assert_eq!(
            tokio::fs::read(dir.path().join(format!("{file_id}.png")))
                .await
                .unwrap(),
            b"png bytes"
        );
        let metadata: librefang_types::media::UploadMetadata = serde_json::from_slice(
            &tokio::fs::read(librefang_types::media::upload_metadata_path(
                dir.path(),
                file_id,
            ))
            .await
            .unwrap(),
        )
        .unwrap();
        assert_eq!(metadata.filename, "generated.png");
        assert_eq!(metadata.content_type, "image/png");
        assert_eq!(metadata.uploaded_by, None);
        assert_eq!(std::fs::read_dir(dir.path()).unwrap().count(), 2);
    }
}
