// Code generated by wit-bindgen-go. DO NOT EDIT.

package net

import (
	"go.bytecodealliance.org/cm"
	"unsafe"
)

// HTTPResponseShape is used for storage in variant or result types.
type HTTPResponseShape struct {
	_     cm.HostLayout
	shape [unsafe.Sizeof(HTTPResponse{})]byte
}

func lower_OptionListU8(v cm.Option[cm.List[uint8]]) (f0 uint32, f1 *uint8, f2 uint32) {
	some := v.Some()
	if some != nil {
		f0 = 1
		v1, v2 := cm.LowerList(*some)
		f1 = (*uint8)(v1)
		f2 = (uint32)(v2)
	}
	return
}

func lower_HTTPRequest(v HTTPRequest) (f0 *uint8, f1 uint32, f2 *uint8, f3 uint32, f4 *[2]string, f5 uint32, f6 uint32, f7 *uint8, f8 uint32) {
	f0, f1 = cm.LowerString(v.Method)
	f2, f3 = cm.LowerString(v.URL)
	f4, f5 = cm.LowerList(v.Headers)
	f6, f7, f8 = lower_OptionListU8(v.Body)
	return
}
