// Code generated by wit-bindgen-go. DO NOT EDIT.

package net

import (
	"go.bytecodealliance.org/cm"
)

// This file contains wasmimport and wasmexport declarations for "librefang:plugin@0.1.0".

//go:wasmimport librefang:plugin/net@0.1.0 fetch
//go:noescape
func wasmimport_Fetch(req0 *uint8, req1 uint32, req2 *uint8, req3 uint32, req4 *[2]string, req5 uint32, req6 uint32, req7 *uint8, req8 uint32, result *cm.Result[HTTPResponseShape, HTTPResponse, HostError])
