// Code generated by wit-bindgen-go. DO NOT EDIT.

// Package net represents the imported interface "librefang:plugin/net@0.1.0".
package net

import (
	"go.bytecodealliance.org/cm"
	hosttypes "librefang.io/plugin/go-env-greet/librefang/plugin/host-types"
)

// HostError represents the type alias "librefang:plugin/net@0.1.0#host-error".
//
// See [hosttypes.HostError] for more information.
type HostError = hosttypes.HostError

// HTTPRequest represents the record "librefang:plugin/net@0.1.0#http-request".
//
// Plain HTTP request. Subject to SSRF guards. Bodies are bytes;
// structured types (JSON etc.) are the plugin's responsibility.
//
//	record http-request {
//		method: string,
//		url: string,
//		headers: list<tuple<string, string>>,
//		body: option<list<u8>>,
//	}
type HTTPRequest struct {
	_       cm.HostLayout             `json:"-"`
	Method  string                    `json:"method"`
	URL     string                    `json:"url"`
	Headers cm.List[[2]string]        `json:"headers"`
	Body    cm.Option[cm.List[uint8]] `json:"body"`
}

// HTTPResponse represents the record "librefang:plugin/net@0.1.0#http-response".
//
//	record http-response {
//		status: u16,
//		headers: list<tuple<string, string>>,
//		body: list<u8>,
//	}
type HTTPResponse struct {
	_       cm.HostLayout      `json:"-"`
	Status  uint16             `json:"status"`
	Headers cm.List[[2]string] `json:"headers"`
	Body    cm.List[uint8]     `json:"body"`
}

// Fetch represents the imported function "fetch".
//
//	fetch: func(req: http-request) -> result<http-response, host-error>
//
//go:nosplit
func Fetch(req HTTPRequest) (result cm.Result[HTTPResponseShape, HTTPResponse, HostError]) {
	req0, req1, req2, req3, req4, req5, req6, req7, req8 := lower_HTTPRequest(req)
	wasmimport_Fetch((*uint8)(req0), (uint32)(req1), (*uint8)(req2), (uint32)(req3), (*[2]string)(req4), (uint32)(req5), (uint32)(req6), (*uint8)(req7), (uint32)(req8), &result)
	return
}
