name = "librefang-visit-counter"
main = "index.js"
compatibility_date = "2025-01-01"

[[d1_databases]]
binding = "DB"
database_name = "librefang-marketplace"
database_id = "91df0bc6-e658-4463-9eba-22d5476d420a"
