#!/usr/bin/env bash
# Reject Claude / Anthropic attribution in every commit a pull request carries.
#
# `scripts/hooks/commit-msg` already encodes the rules, and CI already tests them against a corpus (`scripts/tests/commit-msg-attribution.sh`).
# Neither covers the case this script exists for: **the rules never run on the commits that actually reach `main`.**
#
# Two independent gaps put them there:
#
# 1. `core.hooksPath` is opt-in per clone (`just setup` / `cargo xtask setup`). A fresh clone — or an agent harness working in a worktree nobody ran setup in — has zero git-side enforcement, and the push succeeds.
#
# 2. Even with the hook active on every clone, GitHub's squash-merge composes the merge commit server-side. When a PR's commits have more than one author it appends `Co-authored-by:` trailers for the others, so a single Claude-authored commit anywhere in the branch stamps the squashed commit on `main` with attribution no local hook ever saw.
#
# Gap 2 is why this runs on `pull_request` rather than on `push` to `main`: by the time the trailer exists, the history is already public and the only remedy is a force-push to a protected branch. Refusing the PR is the only point at which the fix is cheap — the author rewrites the branch.
#
# Rules are NOT reimplemented here. This drives the hook once per commit, feeding it that commit's message and identity. The hook reads its message from `$1` and its identity from `git var GIT_AUTHOR_IDENT`, which honours `GIT_AUTHOR_NAME` / `GIT_AUTHOR_EMAIL` — its own comments say so, because that is how an agent harness sets a one-off identity. Copying the regex into a second file is exactly the drift the hook's own comments warn about: a rule spelling "Generated with" sat in front of a footer reading "Generated by" long enough to stamp 285 PRs and issues.
#
# Usage: check-pr-commit-attribution.sh <base-ref> <head-ref>

set -euo pipefail

if [ "$#" -ne 2 ]; then
  echo "usage: $0 <base-ref> <head-ref>" >&2
  exit 2
fi

base="$1"
head="$2"

repo_root=$(cd "$(dirname "$0")/.." && pwd)
hook="$repo_root/scripts/hooks/commit-msg"

if [ ! -x "$hook" ]; then
  echo "FAIL: $hook is missing or not executable — the rules live there, so there is nothing to enforce." >&2
  exit 1
fi

# `merge-base` rather than a plain range so a branch that is merely behind `main` does not re-check commits it did not author.
merge_base=$(git merge-base "$base" "$head")

# One SHA per line — safe to split on newlines, since a SHA never contains one. The commit message itself is read separately per SHA below, so a message containing newlines never enters this list.
commits=$(git rev-list --reverse "$merge_base..$head")

if [ -z "$commits" ]; then
  echo "No commits between $base and $head — nothing to check."
  exit 0
fi

tmpdir=$(mktemp -d)
trap 'rm -rf "$tmpdir"' EXIT

failed=0
count=0

for sha in $commits; do
  count=$((count + 1))
  short=$(git rev-parse --short "$sha")
  msg_file="$tmpdir/$short.msg"
  git log -1 --format=%B "$sha" > "$msg_file"

  author_name=$(git log -1 --format=%an "$sha")
  author_email=$(git log -1 --format=%ae "$sha")
  committer_name=$(git log -1 --format=%cn "$sha")
  committer_email=$(git log -1 --format=%ce "$sha")

  # Author pass: message + author identity, exactly as the hook would have judged the commit at the moment it was made.
  if ! GIT_AUTHOR_NAME="$author_name" GIT_AUTHOR_EMAIL="$author_email" \
       "$hook" "$msg_file" >/dev/null 2>"$tmpdir/$short.err"; then
    echo "── $short — author $author_name <$author_email>" >&2
    sed 's/^/   /' "$tmpdir/$short.err" >&2
    echo "   $(git log -1 --format=%s "$sha")" >&2
    failed=$((failed + 1))
    continue
  fi

  # Committer pass: a rebase or an amend can leave a clean author and a Claude committer, and `git log --format=%cn` is what the GitHub commit list shows for it. Skipped when it matches the author, so the common case does not run the hook twice.
  if [ "$committer_name" != "$author_name" ] || [ "$committer_email" != "$author_email" ]; then
    # An empty message file: the committer pass judges the identity only — the message was already accepted above and re-testing it would double report the same failure.
    : > "$tmpdir/$short.empty"
    if ! GIT_AUTHOR_NAME="$committer_name" GIT_AUTHOR_EMAIL="$committer_email" \
         "$hook" "$tmpdir/$short.empty" >/dev/null 2>"$tmpdir/$short.cerr"; then
      echo "── $short — committer $committer_name <$committer_email>" >&2
      sed 's/^/   /' "$tmpdir/$short.cerr" >&2
      echo "   $(git log -1 --format=%s "$sha")" >&2
      failed=$((failed + 1))
    fi
  fi
done

if [ "$failed" -ne 0 ]; then
  cat >&2 <<EOF

$failed of $count commit(s) in this pull request carry Claude / Anthropic
attribution. This is refused at the pull-request stage on purpose: GitHub's
squash-merge turns a second author into a \`Co-authored-by:\` trailer on the
commit that lands on \`main\`, and no local hook can see that happen.

Rewrite the offending commits under a human identity before merging:

    git rebase $base --exec 'git commit --amend --no-edit --reset-author'
    git push --force-with-lease

If a commit's *message* is what tripped it, reword it in the same rebase.
EOF
  exit 1
fi

echo "OK: $count commit(s) between $base and $head carry no Claude / Anthropic attribution."
