// Code generated by wit-bindgen-go. DO NOT EDIT.

// Package time represents the imported interface "librefang:plugin/time@0.1.0".
package time

// Now represents the imported function "now".
//
// Wall-clock now in SECONDS since the Unix epoch. Subject to
// no capability gating — every plugin can read the clock.
// (Matches the resolution of the underlying
// `host_functions::time_now` dispatch — multiply by 1000 in the
// plugin if you need millis.)
//
//	now: func() -> u64
//
//go:nosplit
func Now() (result uint64) {
	result0 := wasmimport_Now()
	result = (uint64)((uint64)(result0))
	return
}
