// Code generated by wit-bindgen-go. DO NOT EDIT.

package time

// This file contains wasmimport and wasmexport declarations for "librefang:plugin@0.1.0".

//go:wasmimport librefang:plugin/time@0.1.0 now
//go:noescape
func wasmimport_Now() (result0 uint64)
