name: Lint & Build

on:
  push:
    branches: [main,feature/*]
    paths:
      - 'web/**'
  pull_request:
    branches: [main,feature/*]
    paths:
      - 'web/**'

jobs:
  lint-and-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - uses: actions/setup-node@v6
        with:
          node-version-file: 'web/.nvmrc'
          cache: 'pnpm'

      - run: cd web && pnpm install --frozen-lockfile

      - run: cd web && pnpm lint

      - run: cd web && pnpm build
