// Code generated by wit-bindgen-go. DO NOT EDIT.

package agent

import (
	"go.bytecodealliance.org/cm"
)

// This file contains wasmimport and wasmexport declarations for "librefang:plugin@0.1.0".

//go:wasmimport librefang:plugin/agent@0.1.0 send
//go:noescape
func wasmimport_Send(targetAgent0 *uint8, targetAgent1 uint32, body0 *uint8, body1 uint32, result *cm.Result[HostErrorShape, string, HostError])

//go:wasmimport librefang:plugin/agent@0.1.0 spawn
//go:noescape
func wasmimport_Spawn(manifestRef0 *uint8, manifestRef1 uint32, result *cm.Result[HostErrorShape, string, HostError])
