// Code generated by wit-bindgen-go. DO NOT EDIT.

// Package agent represents the imported interface "librefang:plugin/agent@0.1.0".
package agent

import (
	"go.bytecodealliance.org/cm"
	hosttypes "librefang.io/plugin/go-env-greet/librefang/plugin/host-types"
)

// HostError represents the type alias "librefang:plugin/agent@0.1.0#host-error".
//
// See [hosttypes.HostError] for more information.
type HostError = hosttypes.HostError

// Send represents the imported function "send".
//
// Send a message to another agent by id. Returns the host-issued
// message id (opaque string).
//
//	send: func(target-agent: string, body: string) -> result<string, host-error>
//
//go:nosplit
func Send(targetAgent string, body string) (result cm.Result[HostErrorShape, string, HostError]) {
	targetAgent0, targetAgent1 := cm.LowerString(targetAgent)
	body0, body1 := cm.LowerString(body)
	wasmimport_Send((*uint8)(targetAgent0), (uint32)(targetAgent1), (*uint8)(body0), (uint32)(body1), &result)
	return
}

// Spawn represents the imported function "spawn".
//
// Spawn a child agent from a manifest reference. Returns the new
// agent's id.
//
//	spawn: func(manifest-ref: string) -> result<string, host-error>
//
//go:nosplit
func Spawn(manifestRef string) (result cm.Result[HostErrorShape, string, HostError]) {
	manifestRef0, manifestRef1 := cm.LowerString(manifestRef)
	wasmimport_Spawn((*uint8)(manifestRef0), (uint32)(manifestRef1), &result)
	return
}
